### ISSUE TITLE
Brak obrazków w sekcji napojów

### ISSUE THREAD

**Issue by rjfork** [ryszardjanku/cdvRestauracja#7]
Hej,

Wszystkie sekcje w menu oprócz napojów mają dołączone obrazki. Warto by dołączyć obrazek również do napojów. Np obrazek lemoniady.

**Comment by ryszardjanku** [comment]
Commit b9e7f1b naprawia ten błąd

**Comment by ryszardjanku** [comment]
b9e7f1b fixes #7

**Comment by ryszardjanku** [comment]
Otwarte aby przetestować inny sposób zamykania zgłoszeń
